### ISSUE TITLE
Share dumps

### ISSUE THREAD

**Issue by MarkusTeer** [danielkrupinski/VAC#3]
Would you mind sharing the binaries of the modules that you have dumped?

Thank you very much

**Comment by danielkrupinski** [comment]
Here you go [vac_bins.zip](https://github.com/danielkrupinski/VAC/files/4016457/vac_bins.zip)

**Comment by MarkusTeer** [comment]
Hope you don't mind this, just a heads up:
"22_Mon Mar 18 19-23-53 2019.vac" is duplicate of "10_Mon Mar 18 19-26-53 2019.vac"
"23_Mon Mar 18 19-25-33 2019.vac" is duplicate of "11_Mon Mar 18 19-28-33 2019.vac"
"24_Mon Mar 18 19-21-53 2019.vac" is duplicate of "21_Mon Mar 18 19-41-42 2019.vac"
"25_Mon Mar 18 19-57-41 2019.vac" is duplicate of "13_Mon Mar 18 18-18-27 2019.vac"

So in total there are currently 20 unique modules (which also match my own dumps)
