### ISSUE TITLE
VAC

### ISSUE THREAD

**Issue by AlexanderQueen** [danielkrupinski/VAC#4]
Will you try to adapt it for VAC BYPASS? Or it not necessary?

**Comment by danielkrupinski** [comment]
What do you mean?

**Comment by AlexanderQueen** [comment]
I want to know if was changes that can override in a vac wave using vac bypass. I saw that was a lot of updates in VAC section, so i thought that VACBypass needs some adjustment.

**Comment by danielkrupinski** [comment]
Nah, code used in bypass hasn't been changed.
